export type ParsedGeo = { city: string | null; region: string | null };

// Per-market city → region lookup. Keys are lowercase city names; values are
// { city: display-cased, region }. Confident matches only — anything not here
// stays null. Expand over time; partial coverage is acceptable by design.
type CityEntry = { city: string; region: string };
const CITY_TABLES: Record<string, Record<string, CityEntry>> = {
  NO: {
    oslo: { city: "Oslo", region: "Østlandet" },
    asker: { city: "Asker", region: "Østlandet" },
    bærum: { city: "Bærum", region: "Østlandet" },
    drammen: { city: "Drammen", region: "Østlandet" },
    fredrikstad: { city: "Fredrikstad", region: "Østlandet" },
    sarpsborg: { city: "Sarpsborg", region: "Østlandet" },
    moss: { city: "Moss", region: "Østlandet" },
    lillestrøm: { city: "Lillestrøm", region: "Østlandet" },
    hamar: { city: "Hamar", region: "Innlandet" },
    lillehammer: { city: "Lillehammer", region: "Innlandet" },
    gjøvik: { city: "Gjøvik", region: "Innlandet" },
    elverum: { city: "Elverum", region: "Innlandet" },
    bergen: { city: "Bergen", region: "Vestlandet" },
    stavanger: { city: "Stavanger", region: "Vestlandet" },
    sandnes: { city: "Sandnes", region: "Vestlandet" },
    haugesund: { city: "Haugesund", region: "Vestlandet" },
    ålesund: { city: "Ålesund", region: "Vestlandet" },
    førde: { city: "Førde", region: "Vestlandet" },
    jæren: { city: "Jæren", region: "Vestlandet" },
    bryne: { city: "Bryne", region: "Vestlandet" },
    egersund: { city: "Egersund", region: "Vestlandet" },
    trondheim: { city: "Trondheim", region: "Trøndelag" },
    steinkjer: { city: "Steinkjer", region: "Trøndelag" },
    levanger: { city: "Levanger", region: "Trøndelag" },
    namsos: { city: "Namsos", region: "Trøndelag" },
    tromsø: { city: "Tromsø", region: "Nord-Norge" },
    bodø: { city: "Bodø", region: "Nord-Norge" },
    harstad: { city: "Harstad", region: "Nord-Norge" },
    narvik: { city: "Narvik", region: "Nord-Norge" },
    "mo i rana": { city: "Mo i Rana", region: "Nord-Norge" },
    mosjøen: { city: "Mosjøen", region: "Nord-Norge" },
    alta: { city: "Alta", region: "Nord-Norge" },
    hammerfest: { city: "Hammerfest", region: "Nord-Norge" },
    kirkenes: { city: "Kirkenes", region: "Nord-Norge" },
    kristiansand: { city: "Kristiansand", region: "Sørlandet" },
    arendal: { city: "Arendal", region: "Sørlandet" },
    grimstad: { city: "Grimstad", region: "Sørlandet" },
    mandal: { city: "Mandal", region: "Sørlandet" },
    skien: { city: "Skien", region: "Østlandet" },
    porsgrunn: { city: "Porsgrunn", region: "Østlandet" },
    tønsberg: { city: "Tønsberg", region: "Østlandet" },
    sandefjord: { city: "Sandefjord", region: "Østlandet" },
    larvik: { city: "Larvik", region: "Østlandet" },
    kongsberg: { city: "Kongsberg", region: "Østlandet" },
  },
  SE: {
    stockholm: { city: "Stockholm", region: "Svealand" },
    uppsala: { city: "Uppsala", region: "Svealand" },
    västerås: { city: "Västerås", region: "Svealand" },
    örebro: { city: "Örebro", region: "Svealand" },
    göteborg: { city: "Göteborg", region: "Götaland" },
    malmö: { city: "Malmö", region: "Götaland" },
    lund: { city: "Lund", region: "Götaland" },
    helsingborg: { city: "Helsingborg", region: "Götaland" },
    linköping: { city: "Linköping", region: "Götaland" },
    norrköping: { city: "Norrköping", region: "Götaland" },
    jönköping: { city: "Jönköping", region: "Götaland" },
    växjö: { city: "Växjö", region: "Götaland" },
    kalmar: { city: "Kalmar", region: "Götaland" },
    umeå: { city: "Umeå", region: "Norrland" },
    luleå: { city: "Luleå", region: "Norrland" },
    sundsvall: { city: "Sundsvall", region: "Norrland" },
    gävle: { city: "Gävle", region: "Norrland" },
    östersund: { city: "Östersund", region: "Norrland" },
  },
  DK: {
    københavn: { city: "København", region: "Hovedstaden" },
    helsingør: { city: "Helsingør", region: "Hovedstaden" },
    hillerød: { city: "Hillerød", region: "Hovedstaden" },
    roskilde: { city: "Roskilde", region: "Sjælland" },
    holbæk: { city: "Holbæk", region: "Sjælland" },
    køge: { city: "Køge", region: "Sjælland" },
    odense: { city: "Odense", region: "Syddanmark" },
    esbjerg: { city: "Esbjerg", region: "Syddanmark" },
    fredericia: { city: "Fredericia", region: "Syddanmark" },
    vejle: { city: "Vejle", region: "Syddanmark" },
    aarhus: { city: "Aarhus", region: "Midtjylland" },
    horsens: { city: "Horsens", region: "Midtjylland" },
    herning: { city: "Herning", region: "Midtjylland" },
    viborg: { city: "Viborg", region: "Midtjylland" },
    randers: { city: "Randers", region: "Midtjylland" },
    aalborg: { city: "Aalborg", region: "Nordjylland" },
    hjørring: { city: "Hjørring", region: "Nordjylland" },
  },
  FI: {
    helsinki: { city: "Helsinki", region: "Uusimaa" },
    espoo: { city: "Espoo", region: "Uusimaa" },
    vantaa: { city: "Vantaa", region: "Uusimaa" },
    porvoo: { city: "Porvoo", region: "Uusimaa" },
    turku: { city: "Turku", region: "Varsinais-Suomi" },
    tampere: { city: "Tampere", region: "Pirkanmaa" },
    jyväskylä: { city: "Jyväskylä", region: "Keski-Suomi" },
    oulu: { city: "Oulu", region: "Pohjois-Pohjanmaa" },
    kuopio: { city: "Kuopio", region: "Pohjois-Savo" },
    lahti: { city: "Lahti", region: "Päijät-Häme" },
    pori: { city: "Pori", region: "Satakunta" },
    vaasa: { city: "Vaasa", region: "Pohjanmaa" },
    joensuu: { city: "Joensuu", region: "Pohjois-Karjala" },
    lappeenranta: { city: "Lappeenranta", region: "Etelä-Karjala" },
    rovaniemi: { city: "Rovaniemi", region: "Lappi" },
    seinäjoki: { city: "Seinäjoki", region: "Etelä-Pohjanmaa" },
    kotka: { city: "Kotka", region: "Kymenlaakso" },
    mikkeli: { city: "Mikkeli", region: "Etelä-Savo" },
    hämeenlinna: { city: "Hämeenlinna", region: "Kanta-Häme" },
    kouvola: { city: "Kouvola", region: "Kymenlaakso" },
  },
  DE: {
    berlin: { city: "Berlin", region: "Berlin" },
    hamburg: { city: "Hamburg", region: "Hamburg" },
    münchen: { city: "München", region: "Bayern" },
    munich: { city: "München", region: "Bayern" },
    nuremberg: { city: "Nürnberg", region: "Bayern" },
    nürnberg: { city: "Nürnberg", region: "Bayern" },
    augsburg: { city: "Augsburg", region: "Bayern" },
    regensburg: { city: "Regensburg", region: "Bayern" },
    ingolstadt: { city: "Ingolstadt", region: "Bayern" },
    passau: { city: "Passau", region: "Bayern" },
    cologne: { city: "Köln", region: "Nordrhein-Westfalen" },
    köln: { city: "Köln", region: "Nordrhein-Westfalen" },
    düsseldorf: { city: "Düsseldorf", region: "Nordrhein-Westfalen" },
    dortmund: { city: "Dortmund", region: "Nordrhein-Westfalen" },
    essen: { city: "Essen", region: "Nordrhein-Westfalen" },
    aachen: { city: "Aachen", region: "Nordrhein-Westfalen" },
    bonn: { city: "Bonn", region: "Nordrhein-Westfalen" },
    münster: { city: "Münster", region: "Nordrhein-Westfalen" },
    bielefeld: { city: "Bielefeld", region: "Nordrhein-Westfalen" },
    frankfurt: { city: "Frankfurt", region: "Hessen" },
    wiesbaden: { city: "Wiesbaden", region: "Hessen" },
    kassel: { city: "Kassel", region: "Hessen" },
    darmstadt: { city: "Darmstadt", region: "Hessen" },
    stuttgart: { city: "Stuttgart", region: "Baden-Württemberg" },
    mannheim: { city: "Mannheim", region: "Baden-Württemberg" },
    freiburg: { city: "Freiburg", region: "Baden-Württemberg" },
    ulm: { city: "Ulm", region: "Baden-Württemberg" },
    dresden: { city: "Dresden", region: "Sachsen" },
    leipzig: { city: "Leipzig", region: "Sachsen" },
    chemnitz: { city: "Chemnitz", region: "Sachsen" },
    bremen: { city: "Bremen", region: "Bremen" },
    hannover: { city: "Hannover", region: "Niedersachsen" },
    oldenburg: { city: "Oldenburg", region: "Niedersachsen" },
    osnabrück: { city: "Osnabrück", region: "Niedersachsen" },
    kiel: { city: "Kiel", region: "Schleswig-Holstein" },
    lübeck: { city: "Lübeck", region: "Schleswig-Holstein" },
    magdeburg: { city: "Magdeburg", region: "Sachsen-Anhalt" },
    halle: { city: "Halle", region: "Sachsen-Anhalt" },
    erfurt: { city: "Erfurt", region: "Thüringen" },
    rostock: { city: "Rostock", region: "Mecklenburg-Vorpommern" },
    potsdam: { city: "Potsdam", region: "Brandenburg" },
    mainz: { city: "Mainz", region: "Rheinland-Pfalz" },
    koblenz: { city: "Koblenz", region: "Rheinland-Pfalz" },
    trier: { city: "Trier", region: "Rheinland-Pfalz" },
    saarbrücken: { city: "Saarbrücken", region: "Saarland" },
  },
  AT: {
    vienna: { city: "Wien", region: "Wien" },
    wien: { city: "Wien", region: "Wien" },
    graz: { city: "Graz", region: "Steiermark" },
    linz: { city: "Linz", region: "Oberösterreich" },
    salzburg: { city: "Salzburg", region: "Salzburg" },
    innsbruck: { city: "Innsbruck", region: "Tirol" },
    klagenfurt: { city: "Klagenfurt", region: "Kärnten" },
  },
  CH: {
    zürich: { city: "Zürich", region: "Zürich" },
    zurich: { city: "Zürich", region: "Zürich" },
    bern: { city: "Bern", region: "Bern" },
    basel: { city: "Basel", region: "Basel" },
    geneva: { city: "Genève", region: "Genève" },
    genève: { city: "Genève", region: "Genève" },
    lausanne: { city: "Lausanne", region: "Vaud" },
    lucerne: { city: "Luzern", region: "Luzern" },
    luzern: { city: "Luzern", region: "Luzern" },
    fribourg: { city: "Fribourg", region: "Fribourg" },
    neuchâtel: { city: "Neuchâtel", region: "Neuchâtel" },
  },
  UK: {
    london: { city: "London", region: "England" },
    manchester: { city: "Manchester", region: "England" },
    birmingham: { city: "Birmingham", region: "England" },
    liverpool: { city: "Liverpool", region: "England" },
    leeds: { city: "Leeds", region: "England" },
    sheffield: { city: "Sheffield", region: "England" },
    bristol: { city: "Bristol", region: "England" },
    newcastle: { city: "Newcastle", region: "England" },
    nottingham: { city: "Nottingham", region: "England" },
    leicester: { city: "Leicester", region: "England" },
    cambridge: { city: "Cambridge", region: "England" },
    oxford: { city: "Oxford", region: "England" },
    brighton: { city: "Brighton", region: "England" },
    portsmouth: { city: "Portsmouth", region: "England" },
    southampton: { city: "Southampton", region: "England" },
    plymouth: { city: "Plymouth", region: "England" },
    aberdeen: { city: "Aberdeen", region: "Scotland" },
    glasgow: { city: "Glasgow", region: "Scotland" },
    edinburgh: { city: "Edinburgh", region: "Scotland" },
    dundee: { city: "Dundee", region: "Scotland" },
    cardiff: { city: "Cardiff", region: "Wales" },
    swansea: { city: "Swansea", region: "Wales" },
    newport: { city: "Newport", region: "Wales" },
    wrexham: { city: "Wrexham", region: "Wales" },
    belfast: { city: "Belfast", region: "Northern Ireland" },
  },
  IE: {
    dublin: { city: "Dublin", region: "Leinster" },
    cork: { city: "Cork", region: "Munster" },
    limerick: { city: "Limerick", region: "Munster" },
    galway: { city: "Galway", region: "Connacht" },
    waterford: { city: "Waterford", region: "Munster" },
    kilkenny: { city: "Kilkenny", region: "Leinster" },
    sligo: { city: "Sligo", region: "Connacht" },
    athlone: { city: "Athlone", region: "Leinster" },
    tralee: { city: "Tralee", region: "Munster" },
    dundalk: { city: "Dundalk", region: "Leinster" },
    wexford: { city: "Wexford", region: "Leinster" },
    wicklow: { city: "Wicklow", region: "Leinster" },
  },
};

// Trailing descriptors that follow a city in locationNote and should be
// stripped before matching ("Dresden consumer", "Vienna affluent").
const DESCRIPTOR_TAIL =
  /\s+(consumer|affluent|local|quality|premium|free|metro|edition|area|region)\b.*$/i;

export function parseGeo(
  locationNote: string | null | undefined,
  marketCode: string,
): ParsedGeo {
  const table = CITY_TABLES[marketCode];
  if (!table || !locationNote) return { city: null, region: null };
  let note = locationNote.trim();
  if (!note) return { city: null, region: null };

  // For "Asker/Bærum" take the first token; for "Dresden consumer" strip tail.
  note = note.split("/")[0]!.trim();
  note = note.replace(DESCRIPTOR_TAIL, "").trim();
  const key = note.toLowerCase();
  const hit = table[key];
  return hit
    ? { city: hit.city, region: hit.region }
    : { city: null, region: null };
}
